/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resto.team.pbo.view.listPesanan;

import Resto.team.pbo.controller.ListPesananMakananController;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author ALDI
 */
public class DetailListPesanan extends javax.swing.JFrame {

    /**
     * Creates new form detailView
     */
    private ListPesananMakananController controller;
    public DetailListPesanan() {
        initComponents();
    }
    public DetailListPesanan(int id) {
        controller = new ListPesananMakananController(id);
        initComponents();
        controller.setValueTabel(this);
        controller.setDetailPesanan(this);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public JButton getBtnTutup() {
        return btnTutup;
    }

    public JTable getTblPesananM() {
        return tblPesananM;
    }

    public JLabel getTxtBayar() {
        return txtBayar;
    }

    

    public JLabel getTxtMeja() {
        return txtMeja;
    }

    public JLabel getTxtStatus() {
        return txtStatus;
    }

    public JLabel getTxtTgl() {
        return txtTgl;
    }

    public JButton getBtnBayarOrSelesai() {
        return btnBayarOrSelesai;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesananM = new javax.swing.JTable();
        txtStatus = new javax.swing.JLabel();
        txtBayar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBayarOrSelesai = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtMeja = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTgl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnTutup = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Detail pesanan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPesananM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Id Pesanan", "Menu Pesanan", "Jumlah pesanan", "Catatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPesananM);
        if (tblPesananM.getColumnModel().getColumnCount() > 0) {
            tblPesananM.getColumnModel().getColumn(0).setResizable(false);
            tblPesananM.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblPesananM.getColumnModel().getColumn(1).setResizable(false);
            tblPesananM.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblPesananM.getColumnModel().getColumn(2).setResizable(false);
            tblPesananM.getColumnModel().getColumn(2).setPreferredWidth(200);
            tblPesananM.getColumnModel().getColumn(3).setResizable(false);
            tblPesananM.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblPesananM.getColumnModel().getColumn(4).setResizable(false);
            tblPesananM.getColumnModel().getColumn(4).setPreferredWidth(500);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 240));

        txtStatus.setText("di bayar");
        jPanel1.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 290, -1));

        txtBayar.setText("Rp 0");
        jPanel1.add(txtBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 130, -1));

        jLabel4.setText("Jumlah yang harus di bayar");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        btnBayarOrSelesai.setText("BAYAR");
        btnBayarOrSelesai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBayarOrSelesaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBayarOrSelesaiMouseEntered(evt);
            }
        });
        btnBayarOrSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarOrSelesaiActionPerformed(evt);
            }
        });
        jPanel1.add(btnBayarOrSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 120, -1));

        jLabel6.setText("Status");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        txtMeja.setText("M1");
        jPanel1.add(txtMeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 120, -1));

        jLabel9.setText("Meja");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txtTgl.setText("01-01");
        jPanel1.add(txtTgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 300, -1));

        jLabel11.setText("Tanggal Pembelian");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 710, 400));

        btnTutup.setText("Tutup");
        btnTutup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTutupMouseClicked(evt);
            }
        });
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(btnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        getContentPane().add(btnCetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBayarOrSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarOrSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBayarOrSelesaiActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnBayarOrSelesaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBayarOrSelesaiMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnBayarOrSelesaiMouseEntered

    private void btnBayarOrSelesaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBayarOrSelesaiMouseClicked
        // TODO add your handling code here:
        controller.checkTombol(this);
    }//GEN-LAST:event_btnBayarOrSelesaiMouseClicked

    private void btnTutupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTutupMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnTutupMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailListPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailListPesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayarOrSelesai;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnTutup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPesananM;
    private javax.swing.JLabel txtBayar;
    private javax.swing.JLabel txtMeja;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTgl;
    // End of variables declaration//GEN-END:variables
}
