/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Resto.team.pbo.view.login;

import Resto.team.pbo.view.listPesanan.ListPesananIndex;
import Resto.team.pbo.view.makanan.MakananIndex;
import Resto.team.pbo.view.table.indexTable;
import java.awt.Color;

/**
 *
 * @author User
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnList1 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        btnList = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDashboard = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnList1.setBackground(new java.awt.Color(26, 128, 179));
        btnList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnList1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnList1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnList1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnList1MouseReleased(evt);
            }
        });
        btnList1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resto/team/pbo/asset/image/meja21.png"))); // NOI18N
        btnList1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 43, 42));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 204));
        jLabel36.setText("Meja");
        btnList1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, -1));

        jPanel1.add(btnList1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 200, 40));

        btnList.setBackground(new java.awt.Color(26, 128, 179));
        btnList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnListMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnListMouseReleased(evt);
            }
        });
        btnList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resto/team/pbo/asset/image/icons8_list_15px.png"))); // NOI18N
        btnList.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 43, 42));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("List Order");
        btnList.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, -1));

        jPanel1.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 200, 40));

        btnMenu.setBackground(new java.awt.Color(26, 128, 179));
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnMenuMouseReleased(evt);
            }
        });
        btnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resto/team/pbo/asset/image/icons8_tableware_15px.png"))); // NOI18N
        btnMenu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 43, 42));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Menu");
        btnMenu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, 49, -1));

        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 40));

        btnLogout.setBackground(new java.awt.Color(0, 77, 128));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resto/team/pbo/asset/image/icons8_Shutdown_15px.png"))); // NOI18N
        btnLogout.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 43, 40));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("LOGOUT");
        btnLogout.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 13, -1, -1));

        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, -1));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resto/team/pbo/asset/image/icons8_restaurant_40px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel2.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 216, 209));
        jLabel2.setText("Food Application");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 9, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 160, 20));

        btnDashboard.setBackground(new java.awt.Color(26, 128, 179));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDashboardMouseReleased(evt);
            }
        });
        btnDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resto/team/pbo/asset/image/dashboard_icon.png"))); // NOI18N
        btnDashboard.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 43, 42));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Dashboard");
        btnDashboard.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, -1));

        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // TODO add your handling code here:
        btnMenu.setBackground(new Color (52,154, 205));
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // TODO add your handling code here:
         btnMenu.setBackground(new Color (26,128,179));
        
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMousePressed
        // TODO add your handling code here:
        btnMenu.setBackground(new Color (77,179,230));
    }//GEN-LAST:event_btnMenuMousePressed

    private void btnMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseReleased
        // TODO add your handling code here:
        btnMenu.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnMenuMouseReleased

    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(0,52,103));
    }//GEN-LAST:event_btnLogoutMouseEntered

    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        // TODO add your handling code here:
        btnLogout.setBackground(new Color(0,77,128));
    }//GEN-LAST:event_btnLogoutMouseExited

    private void btnListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseEntered
        // TODO add your handling code here:
        btnList.setBackground(new Color (52,154, 205));
    }//GEN-LAST:event_btnListMouseEntered

    private void btnListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseExited
        // TODO add your handling code here:
        btnList.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnListMouseExited

    private void btnListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMousePressed
        // TODO add your handling code here:
        btnList.setBackground(new Color (77,179,230));
    }//GEN-LAST:event_btnListMousePressed

    private void btnListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseReleased
        // TODO add your handling code here:
        btnList.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnListMouseReleased

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        Login login = new Login();
            login.setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList1MouseEntered
        // TODO add your handling code here:
        btnList1.setBackground(new Color (52,154, 205));
    }//GEN-LAST:event_btnList1MouseEntered

    private void btnList1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList1MouseExited
        // TODO add your handling code here:
        btnList1.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnList1MouseExited

    private void btnList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList1MousePressed
        // TODO add your handling code here:
        btnList1.setBackground(new Color (77,179,230));
    }//GEN-LAST:event_btnList1MousePressed

    private void btnList1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList1MouseReleased
        // TODO add your handling code here:
        btnList1.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnList1MouseReleased

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        // TODO add your handling code here:
        btnDashboard.setBackground(new Color (52,154, 205));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        // TODO add your handling code here:
        btnDashboard.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMousePressed
        // TODO add your handling code here:
        btnDashboard.setBackground(new Color (77,179,230));
    }//GEN-LAST:event_btnDashboardMousePressed

    private void btnDashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseReleased
        // TODO add your handling code here:
        btnDashboard.setBackground(new Color (26,128,179));
    }//GEN-LAST:event_btnDashboardMouseReleased

    private void btnList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnList1MouseClicked
        // TODO add your handling code here:
        indexTable indexMeja = new indexTable();
        indexMeja.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnList1MouseClicked

    private void btnListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListMouseClicked
        // TODO add your handling code here:
        ListPesananIndex listIndex = new ListPesananIndex();
        this.setVisible(false);
        listIndex.setVisible(true);
    }//GEN-LAST:event_btnListMouseClicked

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        MakananIndex mak = new MakananIndex();
        mak.setVisible(true);
    }//GEN-LAST:event_btnMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnList;
    private javax.swing.JPanel btnList1;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JPanel btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
